---
OutputDir: "DbAccess"
Namespace: DbCode.Test
NamingJS: "naming.js"
GenerateAsyncCode: true
GenerateAsyncStreamCode: false
GenerateSyncCode: true
ConnectionString: "Server=(LocalDB)\\MSSQLLocalDB; Integrated Security=true;Initial Catalog=CodeGenTestDb;MultipleActiveResultSets=true"
Procedures:
 - SP: dbo.spGetPets
   IgnoreParameters: 
     - ParameterNoOneLikes
 - dbo.spGetPet
 - dbo.spAddPet
 - dbo.spDeletePet
 - dbo.spUpdatePet
 - dbo.spUpdateDog
 - dbo.spSearchPets
 - SP: dbo.spTestBackend
   GenerateAsyncStreamCode: true
 - dbo.spTestNoColumnName
 - dbo.spTestDate
 - dbo.spBuggyProc
 - dbo.spUserNotPermitted
 - dbo.spFile
 - SP: spTestExecuteParams # Execute  if not otherwise possible to get metadata
   ExecuteParameters:
        testId: 1