---
OutputDir: "DbAccess"
Namespace: DbCode.Test
NamingJS: "naming.js"
GenerateAsyncCode: true
GenerateAsyncStreamCode: false
GenerateSyncCode: true
ConnectionString: "Server=(LocalDB)\\MSSQLLocalDB; Integrated Security=true;Initial Catalog=CodeGenTestDb;MultipleActiveResultSets=true"
ReplaceParameters:
   DateOfTool: DateTime.Now
Items:
 - SP: dbo.spGetPets
   IgnoreParameters: 
     - ParameterNoOneLikes
   IgnoreFields:
     - IsNice
   ReplaceParameters:
     ProgramVersion: 4
 - dbo.spGetPet
 - dbo.spAddPet
 - dbo.spDeletePet
 - dbo.spUpdatePet
 - dbo.spUpdateDog
 - dbo.spSearchPets
 - SP: dbo.spTestBackend
   GenerateAsyncStreamCode: true
 - dbo.spTestNoColumnName
 - dbo.spTestDate
 - dbo.spBuggyProc
 - dbo.spUserNotPermitted
 - dbo.spFile
 - SP: imp.spReturnsNothing
   ExecuteOnly: true
 - SP: dbo.spTestExecuteParams # Execute  if not otherwise possible to get metadata
   ExecuteParameters:
        testId: 1
 - View: dbo.Pets