---
OutputDir: "DbAccess"
Namespace: DbCode.Test
NamingJS: "naming.js"
GenerateAsyncCode: true
GenerateAsyncStreamCode: false
GenerateSyncCode: true
ConnectionString: "Server=127.0.0.1;user id=sa;password=abcDEF123#;Initial Catalog=CodeGenTestDb;MultipleActiveResultSets=true;TrustServerCertificate=True;"
ReplaceParameters:
   DateOfTool: DateTime.Now
Items:
 - SP: "[dbo].[spGetPets]"
   IgnoreParameters: 
     - ParameterNoOneLikes
   IgnoreFields:
     - IsNice
   ReplaceParameters:
     ProgramVersion: 4
 - dbo.spGetPet
 - dbo.spAddPet
 - dbo.spDeletePet
 - SP: dbo.spUpdatePet
   MethodName: UpdateThatPet
 - dbo.spUpdateDog
 - dbo.spSearchPets
 - dbo.spSearchPets2
 - SP: dbo.spTestBackend
   GenerateAsyncStreamCode: true
 - dbo.spTestNoColumnName
 - dbo.spTestDate
 - dbo.spBuggyProc
 - dbo.spUserNotPermitted
 - dbo.spFile
 - SP: imp.spReturnsNothing
   ExecuteOnly: true
 - SP: dbo.spTestExecuteParams # Execute  if not otherwise possible to get metadata
   ExecuteParameters:
        testId: 1
 - View: dbo.Pets
 - SP: spReturnAsDict
   ResultType: Dictionary
 - SP: spReturnAsReader
   ResultType: Reader
 - SP:
   ResultType: Result
   SpecificDBNaming: 
    DBSchemaName: Sales.DataDelivery
    DBObjectName: spReturnDataDelivery
   